# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'var1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
def generate_arabic_characters(length=10):
    arabic_characters = [chr(i) for i in range(0x0600, 0x06FF)]
    return ''.join(random.choice(arabic_characters) for _ in range(length))
arabic_string = generate_arabic_characters()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("font: 75 italic 10pt \"Times New Roman\";")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 220, 75, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 100, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 italic 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 100, 21, 21))
        self.label_2.setStyleSheet("font: 75 italic 14pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(230, 140, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 140, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 italic 12pt \"Times New Roman\";\n"
"color: rgb(170, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(180, 180, 181, 16))
        self.label_4.setStyleSheet("font: 75 italic 14pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.Formula = QtWidgets.QLabel(Form)
        self.Formula.setGeometry(QtCore.QRect(10, 270, 91, 16))
        self.Formula.setStyleSheet("font: 75 italic 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 255);")
        self.Formula.setObjectName("Formula")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", arabic_string+" Периметр параллелограмма "))
        self.pushButton.setText(_translate("Form", "Очистить"))
        self.pushButton_2.setText(_translate("Form", "Вычислить"))
        self.label.setText(_translate("Form", "А"))
        self.label_2.setText(_translate("Form", "В"))
        self.label_3.setText(_translate("Form", "Периметр параллелограмма"))
        self.label_4.setText(_translate("Form", "P ="))
        self.Formula.setText(_translate("Form", "P = 2(a+b)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
