# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '02Dec.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 349)
        Form.setStyleSheet("\n"
"")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(0, 330, 501, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    font: 75 italic 12pt \"Times New Roman\";\n"
"    \n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: purple;\n"
"    width: 10px;\n"
"    margin: 1px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 111, 51))
        self.pushButton.setStyleSheet("font: 75 italic 12pt \"Times New Roman\";\n"
"color: rgb(170, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -80, 641, 511))
        self.label.setStyleSheet("image:url(:/da/backiee-308662-landscape.jpg)")
        self.label.setObjectName("label")
        self.label.raise_()
        self.progressBar.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Загрузить"))
        self.label.setText(_translate("Form", "TextLabel"))
from Dec2 import photo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
